# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SwiftGL
url: "http://swiftgl.org"
description: > # this means to ignore newlines
  Swift Graphics Libraries. OpenGL and more for everyone.

# Build settings
markdown: kramdown

github: [metadata]
kramdown:
 input: GFM
 hard_wrap: false
 ## below are fixed on gh-pages
 lsi: false
 safe: true
 highlighter: rouge
 gist:
   noscript: false
gems:
 - jekyll-coffeescript
 - jekyll-paginate
